[build]
commands = [
  "npm install --prefix backend",
  "npm install --prefix frontend",
  "npm run build --prefix frontend",
  "npm run build --prefix backend"
]

[start]
cmd = "npm start --prefix backend"
